### ISSUE TITLE
node-gyp rebuild fails on OS X

### ISSUE THREAD

**Issue by kylesimmonds** [atom/node-minidump#17]
I originally posted this in atom/atom#12120, but after trying to install minidump globally outside of Atom I realized the issue isn't Atom related.

FWIW, I installed Node through Homebrew and used [this method](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md) to use NPM without sudo. Up until now I haven't had issues installing and using modules.

Here's the log:

    ~ > npm install -g minidump
    /usr/local/bin/minidump_stackwalk -> /usr/local/lib/node_modules/minidump/bin/minidump_stackwalk

    > minidump@0.9.0 install /usr/local/lib/node_modules/minidump
    > node-gyp rebuild

      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf/bytereader.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf_cfi_to_module.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf_cu_to_module.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf/dwarf2diehandler.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf/dwarf2reader.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/dwarf_line_to_module.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/language.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/mac/arch_utilities.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/mac/dump_syms.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/mac/file_id.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/mac/macho_id.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/mac/macho_reader.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/mac/macho_utilities.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/mac/macho_walker.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/md5.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/module.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/stabs_reader.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/common/stabs_to_module.o
      CXX(target) Release/obj.target/dump_syms/deps/breakpad/src/tools/mac/dump_syms/dump_syms_tool.o
      LINK(target) Release/dump_syms
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/basic_code_modules.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/basic_source_line_resolver.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/binarystream.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/call_stack.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/cfi_frame_info.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/disassembler_x86.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/dump_context.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/dump_object.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/logging.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/pathname_stripper.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/process_state.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/simple_symbol_supplier.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/source_line_resolver_base.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stack_frame_cpu.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stack_frame_symbolizer.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalk_common.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_amd64.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_arm.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_arm64.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_mips.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_ppc.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_ppc64.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_sparc.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/stackwalker_x86.o
      CXX(target) Release/obj.target/stackwalk_common/deps/breakpad/src/processor/tokenize.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_implicit.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_insn.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_invariant.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_modrm.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_opcode_tables.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_operand.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_reg.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/ia32_settings.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/x86_disasm.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/x86_format.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/x86_imm.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/x86_insn.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/x86_misc.o
      CC(target) Release/obj.target/stackwalk_common/deps/breakpad/src/third_party/libdisasm/x86_operand_list.o
      LIBTOOL-STATIC Release/stackwalk_common.a
    libtool: unrecognized option `-static'
    libtool: Try `libtool --help' for more information.
    make: *** [Release/stackwalk_common.a] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
    gyp ERR! stack     at emitTwo (events.js:106:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
    gyp ERR! System Darwin 15.5.0
    gyp ERR! command "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /usr/local/lib/node_modules/minidump
    gyp ERR! node -v v6.3.0
    gyp ERR! node-gyp -v v3.3.1
    gyp ERR! not ok 
    npm ERR! Darwin 15.5.0
    npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "install" "-g" "minidump"
    npm ERR! node v6.3.0
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE

    npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the minidump package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs minidump
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls minidump
    npm ERR! There is likely additional logging output above.

**Comment by kylesimmonds** [comment]
So the issue was in the `libtool` executable, which should be the system's but for me was in MAMP. Fixed by adding a symlink to the system executable in MAMP's /Library/bin directory. This may or may not also be a problem for other applications that require precedence in your `$PATH`.
