### ISSUE TITLE
won't build on ARM without a manual include

### ISSUE THREAD

**Issue by anomaly256** [atom/node-minidump#5]
It apparently tries to find a variable named 'chromeos' if on arm, which isn't set anywhere
```
gyp: name 'chromeos' is not defined while evaluating condition 'target_arch=="arm" and chromeos==1' in deps/breakpad/breakpad.gyp while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.8.13.23
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/anomaly/node_modules/minidump
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm ERR! minidump@0.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.7.0 install script.
npm ERR! This is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.
```
Adding this to ~/.gyp/include.gypi works around it:
```
{
  'variables': {
    'chromeos%': 0
  }
}
```
or, I assume, set that to '1' if actually on ChromeOS

**Comment by anomaly256** [comment]
Thanks, will try it out soon

**Comment by jlord** [comment]
I'm getting this issue building Atom from `master` on Chromebook: 32bit ARM, Ubuntu 14.04 with Xfce

**Comment by zcbenz** [comment]
@jlord I think it might be caused that atom is using node-minidump 0.8.

**Comment by jlord** [comment]
@zcbenz can we update it? I'd bump the ver myself but I searched the repo and don't see where we're requiring node-minidump?

**Comment by zcbenz** [comment]
@jlord Yeah we can, 0.9 is a quite minor update. In Atom node-minidump is used by the `dump-symbols-task.coffee`.

**Comment by zcbenz** [comment]
Closing since it works in 0.9.
